## Connects your game to the Oyun Takımı site. Do not edit this file.
## Oyununu siteye bağlar. Lütfen bu dosyayı değiştirme.
##
## It is an autoload, so you can use it from any script as `Oyun`:
##   Oyun.get_language()                  -> "tr" or "en"
##   var player = await Oyun.get_player() -> { "nickname": ... } or null when not signed in
##   var best = await Oyun.submit_score(42) -> best score (or -1 if it failed)
##   Oyun.paused.connect(func(): ...)     the player switched tabs: the game is paused for you
##   Oyun.resumed.connect(func(): ...)
##
## When the game runs in the Godot editor or without the site ("preview"), scores are only
## kept on this computer.
extends Node

signal paused
signal resumed
signal _answer(value)

var _sdk: JavaScriptObject = null
var _callbacks: Array = [] # keeps JavaScript callbacks alive


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	if OS.has_feature("web"):
		_sdk = JavaScriptBridge.get_interface("OyunSDK")
	if _sdk:
		_sdk.onPause(_callback(func(_args): _set_paused(true)))
		_sdk.onResume(_callback(func(_args): _set_paused(false)))
	else:
		print("[Oyun] Önizleme modu / preview mode")


## "platform" on the site, "preview" anywhere else.
func get_mode() -> String:
	return str(_sdk.mode) if _sdk else "preview"


func get_language() -> String:
	if _sdk:
		return str(_sdk.getLanguage())
	return "en" if OS.get_locale_language() == "en" else "tr"


func get_player() -> Variant:
	if not _sdk:
		return null
	var result = await _call(_sdk.getPlayer())
	if result == null:
		return null
	return { "nickname": str(result.nickname) }


func submit_score(score: int) -> int:
	if not _sdk:
		return _preview_score(score)
	var result = await _call(_sdk.submitScore(max(score, 0)))
	return int(result.best) if result != null else -1


func _set_paused(value: bool) -> void:
	get_tree().paused = value
	if value:
		paused.emit()
	else:
		resumed.emit()


func _callback(fn: Callable) -> JavaScriptObject:
	var cb := JavaScriptBridge.create_callback(fn)
	_callbacks.append(cb)
	return cb


# Waits for a JavaScript promise. Resolves to its value, or null if it failed.
func _call(promise: JavaScriptObject) -> Variant:
	var done := [false, null]
	var finish := func(value):
		if not done[0]:
			done[0] = true
			done[1] = value
			_answer.emit(value)
	promise.then(_callback(func(args): finish.call(args[0])), _callback(func(args):
		push_warning("OyunSDK: " + str(args[0]))
		finish.call(null)))
	while not done[0]:
		await _answer
	return done[1]


func _preview_score(score: int) -> int:
	var path := "user://preview_best.txt"
	var best := 0
	if FileAccess.file_exists(path):
		best = int(FileAccess.get_file_as_string(path))
	if score > best:
		best = score
		var f := FileAccess.open(path, FileAccess.WRITE)
		f.store_string(str(best))
	print("[Oyun] Önizleme / preview: %d (en iyi / best %d)" % [score, best])
	return best
